#OutputRequestBuilder properties
bssContent = content-bss
cmsUrl = /design-system/1_0_0/en-us/dist/bss-outputs/application.json
template = template
templateEngine = simple-content-engine
mainTemplate = blt5e564cebdea47884
mainTemplatePhase2=blt72871aecde1e4705
planOfferingsMainTemplate = blt746077a23b76400c
