
jdbc.driverClassName=oracle.jdbc.driver.OracleDriver

jdbc.url.bib.hp=jdbc:oracle:thin:@dbhpbib.trinet.com:2953:hpbib
jdbc.url.bib.hr=jdbc:oracle:thin:@dbhrbib.trinet.com:2963:hrbib

jdbc.url.cab.hp=jdbc:oracle:thin:@dbhpcab.trinet.com:1757:hpcab
jdbc.url.cab.hr=jdbc:oracle:thin:@dbhrcab.trinet.com:1910:hrcab

jdbc.url.lites.hr=jdbc:oracle:thin:@dbhrlites.trinet.com:1725:hrlites
jdbc.url.lites.hp=jdbc:oracle:thin:@dbhplites.trinet.com:1749:hplites

jdbc.url.val.hr=jdbc:oracle:thin:@dbhrval.trinet.com:2967:hrval
jdbc.url.val.hp=jdbc:oracle:thin:@dbhpval.trinet.com:2957:hpval

jdbc.url.val.hr=jdbc:Oracle:thin:@dbhrval.trinet.com:2967:hrval
jdbc.url.val.hp=jdbc:Oracle:thin:@dbhpval.trinet.com:2957:hpval
jdbc.url.val.cr=jdbc:Oracle:thin:@dbcrval.trinet.com:2927:crcval
#
jdbc.url.itqa.hr=jdbc:oracle:thin:@dbhritqa.trinet.com:2964:hritqa
jdbc.url.itqa.hp=jdbc:oracle:thin:@dbhpitqa.trinet.com:2954:hpitqa
jdbc.url.itqa.cr=jdbc:oracle:thin:@dbcritqa.trinet.com:2924:critqa

jdbc.hr.lites.username=sysadm
jdbc.hr.lites.password=mhall510

jdbc.hp.lites.username=hrdb
jdbc.hp.lites.password=starfish510400

jdbc.hr.val.username=
jdbc.hr.val.password=

jdbc.hp.cab.username=
jdbc.hp.cab.password=

jdbc.hr.cab.username=
jdbc.hr.cab.password=

jdbc.hp.val.username=hrdb
jdbc.hp.val.password=cobia727337

#Report DB Parameters
myssql_url = jdbc:mysql://10.30.26.55:3306/trinet_automation_db
mysql_username=aotusvc
mysql_password=@ut0M@te
report_database=on

#VM hub url
vmhub_url=http://10.30.26.50:4444/wd/hub
runremotely=off

#Report DB Parameters
myssql_url = jdbc:mysql://10.30.26.55:3306/trinet_automation_db
mysql_username=aotusvc
mysql_password=@ut0M@te
report_database=off
generate_testReport = on

#project name
project=API Automation

## email flag to send automation report 
email = off
mailto = suma.chanda@trinet.com
mailfrom =suma.chanda@trinet.com
