
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd/">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Style-Type" content="text/css">
    <style> 
      p { font-family: Arial, sans-serif, 'Open Sans';}
      td { font-family: Arial, sans-serif, 'Open Sans';}
    </style>
</head>

<body>



<#-- padding: top, right, bottom, left (clockwise, starting at top) -->

<#if debug == true>
    <h3>generated by Freemarker on ${.now}</h3>
</#if>

<#setting locale="en_US">
<#setting number_format="0.####">

<#global tab = '&nbsp;&nbsp;'>
<#global font = "font-family: Arial, sans-serif, 'Open Sans';">
<#global colorZebra = '#F4F6F7'>
<#global colorBlue = '#0077BC'>
<#global colorGray = '#697382'>

<img src="${emailContentBaseUrl}email_banner.jpg" alt="Email-Banners"/>

<#-- Header -->
<#include '/headerBdm.ftl'>

</body>

</html>