
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd/">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Content-Style-Type" content="text/css"/>
    
<style> 
    p { font-family: Arial, sans-serif, 'Open Sans';}
    td { font-family: Arial, sans-serif, 'Open Sans';}
</style>
    
</head>

<body>

<#-- padding: top, right, bottom, left (clockwise, starting at top) -->

<#if debug == true>
    <h3>generated by Freemarker on ${.now}</h3>
</#if>

<#setting locale="en_US">
<#setting number_format="0.####">

<#global tab = '&nbsp;&nbsp;'>
<#global font = "font-family: Arial, sans-serif, 'Open Sans';">
<#global colorZebra = '#F4F6F7'>
<#global colorBlue = '#0077BC'>
<#global colorGray = '#697382'>

<img src="${emailContentBaseUrl}email_banner.jpg" alt="Email-Banner"/>

<#assign TriNetI   = 5>
<#assign TriNetII  = 4>
<#assign TriNetIII = 3>
<#assign TriNetIV  = 1>
<#assign TriNetXI  = 2>

<#-- Header -->
<#if renewal == 'true'>
    <#include '/header.ftl'>
<#else>
    <#include '/newClientHeader.ftl'>
</#if>
<br/>
<#include '/budgetAndStrategy.ftl'>
<br/>
<#if hsaFunding?has_content>
    <#if (hsaFunding.optionId?has_content && hsaFunding.optionId > 0)>
        <header>
            <h3>Health Savings Account (HSA) Contributions (All Benefit Groups)</h3>
        </header>
        <#include '/hsa.ftl'>
    </#if>
</#if>

<#--  Medical header is at the top outside the Benefit Group loop -->
<#if exchange != TriNetXI>
    <#include '/medicalHeader.ftl'>
<#else>
    <br/>
    <table border='1'  style="border-width: 0px; margin-left:10px; border-collapse: collapse;">
        <tr>
            <td style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 15px; background-color: #0077BC; color:white;">
                <p><strong>Not offering Trinet Medical Coverage</strong></p>
            </td>
        </tr>
    </table>
</#if>

<#-- obamaCare -->
<#if exchange == TriNetI || exchange == TriNetII || exchange == TriNetIV>
    <#if isEligAle == 'true'>
        <#include '/obamaCare.ftl'>
    </#if>
</#if>
<br/>

<#-- Benefit Group loop -->
<#list benefitGroups as benefitGroup>


    <#global bg = benefitGroup>
    <#global bgIndex = benefitGroup?index>
    <p></p>
    <header>
        <h2>Benefit Group: ${benefitGroup.name}</h2>
    </header>
    
    <table border='1'  style="border-width: 0px; border-collapse: collapse;">
        <tr>
        <td  colspan='2' style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 15px; background-color: #0077BC; color:white;">
            <p><strong>Wait Period and Default Benefit Group</strong></p>
        </td>
        </tr>
        <tr>
            <td width='170' style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 5px;">
                <p>Wait Period:</p>
            </td>
            <td width='430' style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 5px;">
                <p>${benefitGroup.waitPeriodDescr} </p>
            </td>
        </tr>
        <tr style="background-color: #F4F6F7;">
            <td width='170' style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 5px;">
                <p>Default Benefit Group:</p>
            </td>
            <td width='430' style="border-width : 1px; border-color: #bfbfbf; border-style: solid; padding: 1px 5px 1px 5px;">
                <p>${benefitGroup.defaultGroup?string('Yes', 'No')} </p>
            </td>
        </tr>
    </table>
    
    <#include '/benefitGroup.ftl'>
    
</#list>

<#-- Footer -->
<#if renewal == 'true'>
    <#include '/renewalFooter.ftl'>
<#else>
    <#include '/newClientFooter.ftl'>
</#if>

</body>

</html>